# Generated by Django 4.1.1 on 2022-10-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='user',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='street',
        ),
        migrations.AddField(
            model_name='shift',
            name='addressbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_addressbook', to='core.addressbook'),
            preserve_default=False,
        ),
    ]
