# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.AddField(
            model_name='nurse',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.addressbook'),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='alt_line',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='country',
            field=models.CharField(default='Suomi', max_length=64),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None),
        ),
    ]
