# Generated by Django 4.1.1 on 2022-10-16 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='shift',
            name='finish_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 16, 15, 0, 21, 980936, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_org_name', to='core.employer'),
        ),
    ]
