# Generated by Django 4.1.1 on 2022-10-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_rn',
            field=models.BooleanField(default=False),
        ),
    ]
