# Generated by Django 4.1.1 on 2022-10-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nurse_is_rn'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
