# Generated by Django 4.1.1 on 2022-11-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_bios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_date',
        ),
    ]
