# Generated by Django 4.1 on 2022-10-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shift_finish_time_shift_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employer_id', to='core.employer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_org_name', to='core.employer'),
        ),
    ]
