# Generated by Django 4.1 on 2022-10-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shift_employer_id_alter_shift_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employer_id',
        ),
    ]
