# Generated by Django 4.1.1 on 2022-10-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_phone_number_nurse_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
