# Generated by Django 4.1.1 on 2022-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
