# Generated by Django 4.1.1 on 2022-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_shift_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
