# Generated by Django 4.1.1 on 2022-12-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shift_finish_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_street', to='core.addressbook'),
        ),
    ]
