# Generated by Django 4.1.1 on 2022-10-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_phone_number_employer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.addressbook'),
        ),
    ]
