# Generated by Django 4.1.1 on 2022-10-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift_user_alter_shift_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shift_nurse', to='core.nurse'),
        ),
    ]
