# Generated by Django 4.1.1 on 2022-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shift_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='time_reserved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
