# Generated by Django 4.1.1 on 2022-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shift_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='role',
            field=models.CharField(choices=[('RN', 'RN'), ('PN', 'PN'), ('AS', 'AS')], max_length=2),
        ),
    ]
