# Generated by Django 4.1.1 on 2022-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shift_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='role',
            field=models.CharField(choices=[('RN', 'RN'), ('PN', 'PN'), ('ASST', 'ASST')], max_length=4),
        ),
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(choices=[('RN', 'RN'), ('PN', 'PN'), ('ASST', 'ASST')], max_length=4),
        ),
    ]
