# Generated by Django 4.1.1 on 2022-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_nurse_role_alter_shift_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_date',
            field=models.DateTimeField(),
        ),
    ]
