# Generated by Django 4.1.1 on 2022-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_shift_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
