# Generated by Django 4.1.1 on 2022-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shift_shift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='fullname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
