# Generated by Django 4.1.1 on 2022-11-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_nurse_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='fullname',
        ),
    ]
