# Generated by Django 4.1.1 on 2022-11-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_nurse_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
