# Generated by Django 4.1.1 on 2022-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_shift_finish_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift_date',
            new_name='shift_start_date',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
