# Generated by Django 4.1.1 on 2022-11-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_shift_date_shift_shift_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='EndDate'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start_date',
            field=models.DateTimeField(verbose_name='StartDate'),
        ),
    ]
