# Generated by Django 4.1.1 on 2022-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_shift_shift_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='EndDate'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_start_date',
            field=models.DateField(verbose_name='StartDate'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
