# Generated by Django 4.1.1 on 2022-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_shift_shift_end_date_alter_shift_finish_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_start_date',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(null=True, verbose_name='Shift Date'),
        ),
    ]
